version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb+srv://Surya:surya02816@sems.kn82z.mongodb.net/mycruddb?retryWrites=true&w=majority&appName=SEMS"
      JWT_SECRET: "yourSuperSecretKey123"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
